### ISSUE TITLE
Issue with running EmpTransfo code 

### ISSUE THREAD

**Issue by sandeep3119** [roholazandie/EmpTransfo#7]
Got an error with initial setup and code reproducing. Please help me out running the code.

INFO:train_multihead.py:Build inputs and labels
INFO:train_multihead.py:Pad inputs and convert to Tensor
Traceback (most recent call last):
  File "train_multihead.py", line 308, in <module>
    train()
  File "train_multihead.py", line 204, in train
    train_loader, val_loader, train_sampler, valid_sampler = get_data_loaders(config, tokenizer)
  File "train_multihead.py", line 147, in get_data_loaders
    tensor = torch.tensor(dataset[input_name])
TypeError: an integer is required (got type list)

**Comment by juanmaoxiongmaoQAQ** [comment]
I also encountered the same problem, did you solve it? How to solve it?thanks

**Comment by Banana-lwz** [comment]
> I also encountered the same problem, did you solve it? How to solve it?thanks

Have you solved this problem yet? I also encountered this problem, I do not know where the problem lies nali

**Comment by Banana-lwz** [comment]
> I also encountered the same problem, did you solve it? How to solve it?thanks
Hello, have you solved this problem now?
